version: "3.8"
services:
  redis:
    image: redis
    container_name: Redis
    environment:
      - TZ=Asia/Shanghai
    command:
      - --requirepass
      - TaqbY9rs3Mc8tjhKAxYwwJjXOrby6i7twDd1g7rgrzAJU0p8MP
  nginx:
    image: nginx
    container_name: Nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8080:8080
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - app
  app:
    build: ./app
    container_name: testFrame
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./app:/app
    links:
      - redis